server:
  port: 7777

spring:
  application:
    name: penguins
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penguins?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Zb@123456
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 328364133@qq.com
    # 配置密码，注意不是真正的密码，而是授权码
    password: otubpzulezfdcaeg
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #     配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  configuration:
    #    map-underscore-to-camel-case: true
    #    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #  global-config:
    # 逻辑删除配置
    #    db-config:
    #      id-type: auto
    #      logic-delete-field: isDeleted
    #      logic-delete-value: 1
    #      logic-not-delete-value: 0
    #  mapper-locations: classpath*:mappers/**/*Mapper.xml



