server:
  port: 7777

spring:
  application:
    name: penguins
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penguins?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Zb@123456
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
#  security:
#    user:
#      name: admin
#      password: 123456

knife4j:
  enable: true
  setting:
    enableDynamicParameter: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    #    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      id-type: auto
    banner: false
    
debug: true

