spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/penguins?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Zb@123456

knife4j:
  enable: true
  setting:
    enableDynamicParameter: true
  production: false

#debug: true

minio:
  host: http://101.33.240.92:9000
  web-host: http://101.33.240.92:9000
  bucket: wms
  access-key: kFR1787noBboUq4E
  access-secret: sbmdVVe6WoVzAVZG5S2Yx2S7F1BtnOGU
