knife4j:
  enable: true
  setting:
    enableDynamicParameter: true
  production: false

#debug: true
#logging:
#  level:
#    root: debug
spring:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
        - USER
